name: HNG Stage 2 CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create env file for CI
        run: cp api/.env .env


      - name: Build and Start Containers
        run: docker-compose up -d --build
        env:
          REDIS_HOST: redis
          API_URL: http://api:8000

      - name: Wait for Healthchecks
        run: |
          echo "Waiting for services to become healthy..."
          # Increased to 20 attempts (100 seconds total)
          attempt=0
          until [ $(docker ps | grep "(healthy)" | wc -l) -ge 3 ] || [ $attempt -gt 20 ]; do
            echo "Attempt $attempt: Waiting for containers to be healthy..."
            sleep 5
            attempt=$((attempt+1))
            docker ps # This prints the status so you can see which one is failing
          done

          if [ $(docker ps | grep "(healthy)" | wc -l) -lt 3 ]; then
            echo "Healthcheck timeout reached!"
            docker compose logs
            exit 1
          fi

      - name: Integration Test - Submit Job
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:3000/submit)
          echo "Response: $RESPONSE"
          if [[ $RESPONSE != *"job_id"* ]]; then
            echo "Job submission failed!"
            exit 1
          fi

      - name: Clean Up
        if: always()
        run: docker-compose down
